### ISSUE TITLE
Division by zero produces 0

### ISSUE THREAD

**Issue by Zueuk** [mvhooren/JitCat#11]
Even 0/0

**Comment by mvhooren** [comment]
This is intentional behaviour for the use case for which this library was originally developed, which is game development. NaN can spread like a disease through your application and will lead to much worse failure modes than simply returning 0. It is of course not mathematically correct to return 0. 

I would like this library to support more use cases and therefore this behaviour should be optional and not enabled by default. The default behaviour will then become the same as C++ as defined in the IEEE-754 standard where division by zero will return NaN or +/- infinity depending on the numerator.

**Comment by mvhooren** [comment]
This is now an option defined in Configuration.h: divisionByZeroYieldsZero. By default the option is turned off and floating point division by zero conforms to IEEE-754 and integer division is undefined behaviour as it is in C++.
